# Generated by Django 5.0.4 on 2025-01-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_level', models.IntegerField(default=0)),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('oxygen', models.FloatField(default=0.0)),
                ('pollution', models.FloatField(default=0.0)),
                ('ozone', models.IntegerField(default=0)),
                ('light', models.IntegerField(default=0)),
                ('uv_light', models.FloatField(default=0.0)),
                ('quality', models.IntegerField(default=0)),
                ('current_date_time', models.DateTimeField()),
                ('flow_rate', models.FloatField(default=0.0)),
                ('total_milli_liters', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('liquid_level', models.IntegerField(default=0)),
                ('tds_value', models.FloatField(default=0.0)),
            ],
        ),
    ]
